### PR TITLE
Basic electron wrapping

### PR DESCRIPTION
**Pull request by zhfuzzy**
Use electron as a file server.

### CODE REVIEW

**Comment by bushare** [comment]
On Linux/Mac:
```bash
npm install -g electron-prebuilt
# build as usual
npm run build
# in repo's root folder
electron .
```
On windows you have to copy `img` and `font` from `src/skins/vector` to `vector`, for windows doesn't recognize soft links

**Comment by ara4n** [comment]
There's also work been going on by @krisak at https://github.com/krisak/vector-electron-desktop. I like the fact that this adds the electron stuff into the main vector-web tree, but I think @krisak may have got a bit further in terms of features.  I'd be happy to merge it in here as part of the official distro if we can find a way to get best of both!

**Comment by krisak** [comment]
@zhfuzzy there are few things that can be done without going into vector-web to make the client better. It has to do with how the windows work and also having the tray icon on windows/linux. 

If you want join forces we can discuss this maybe at #vector@matrix.org to make best possible client?

**Comment by zhfuzzy** [comment]
Surely it's a better idea to place electron releated stuff in some other place, electron is not as simple as I thought in the begining.

Having a seperating repo, we can focus on:

- Packaging for OSs
- Resolving electron related issue (I just found that downloading doesn't not work well in electron)
- Leveraging the multi-window capability of electron
- Making some OS related UI outside of the vector's box.

We may talk in the matrix.

**Pull request closed without merging**
