### PR TITLE
Implement reorderable rooms via room tagging.

### PR DESCRIPTION
**Pull request by ara4n**
Currently depends on the room tagging branch of matrix-js-sdk, which should hopefully be merged soon (https://github.com/matrix-org/matrix-js-sdk/pull/39).

The only known problem here is that the DnD wrapping on MatrixChat seems to break the Controller mixin, causing:

Uncaught TypeError: window.matrixChat.showScreen is not a function  index.js:84

Thoughts welcome on how to resolve that.

### CODE REVIEW

**Comment by ara4n** [comment]
mental note for myself: need to test the CallView preview which has been moved out into LeftPanel.

**Comment by ara4n** [comment]
and i need to make all the debug configurable

**Comment by ara4n** [comment]
Another known issue is that if you de-tag a room by dragging it to 'Conversations' and then tag a different room from 'Conversations' by dragging it elsewhere, the conversations view will update to show neither room.  I believe this is because of SYN-513: as the server doesn't relay de-tagging to us, the js-sdk state gets out of sync with the UI and thinks the rooms are still tagged.  When the tag operation /does/ cause a UI refresh, it thus shows the wrong UI state.

**Comment by dbkr** [comment]
Had a chat IRL about the fact that this diverges RoomList controller quite significantly from the react-sdk base: this is something we're trying to address in a broader scope. LGTM once the exception caused by MatrixChat drag/drop wrapping is fixed & conflicts merged.

**Comment by ara4n** [comment]
MatrixChat dnd wrapping fixed by bea6408.  Will fix conflicts and merge.

**Pull request merged**
