### PR TITLE
Fix changelog links

### PR DESCRIPTION
**Pull request by remram44**
Link to the HTML commit page instead of API JSON, and open in new window instead of replacing the Vector tab.

Fixes #2056

### CODE REVIEW

**Comment by ara4n** [comment]
This is what I tried previously in https://github.com/remram44/vector-web/commit/c6d4eb7fd3f593a746c9142db0c1cd33e7b58ae0#diff-e5d019d31cc73c9ba4bec9ad117c6b84 but it didn't work - I haven't had a chance to dig to see why.

**Comment by remram44** [comment]
I don't know how to trigger this changelog feature...

**Comment by ara4n** [comment]
on a local instance you set a the /version file that doesn't match the app's internal version idea - look at vector.im/develop/version for an example one

**Comment by richvdh** [comment]
Fixed with the help of https://github.com/vector-im/vector-web/commit/6cb7ffcd3baae236ad128d3745bbd3b7fd8a3ee5. Thanks for the PR!

**Pull request merged**
