### PR TITLE
Wmwragg/chat message presentation

### LINKED ISSUE #1748: Chat message states: implement new style
Chat message states: implement the 6 different message states (style change) as per design

Notes:
- time appears inline with name always, but only for 1st message
- ellipses only on hover over
- people aligned on 1st line (bottom)

- Design: small tweaks and assets need to be marked ready

### PR DESCRIPTION
**Pull request by wmwragg**
This should close #1748. A companion branch matrix-org/matrix-react-sdk:wmwragg/chat-message-presentation also needs to be merged.

Signed-off-by: William Wragg wm.wragg@gmail.com

### CODE REVIEW

**Comment by wmwragg** [comment]
The actions have the avatar outset, as as we aren't doing the full user lozenge yet we needed to differentiate these from normal continuation messages with an emoji at the beginning, as the emoji will be the same size as the avatar now
screen shot 2016-08-19 at 15 26 39

**Comment by ara4n** [comment]
Focusing on the design implementation rather than the code right now whilst playing with it, this is almost perfect - thanks!  The only two remaining things I've spotted are shown below:

layout-fun

**Comment by ara4n** [comment]
codewise this lgtm :)

**Comment by wmwragg** [comment]
@ara4n OK, I've tweaked the positions:
screen shot 2016-08-22 at 10 45 42

and reduced the distance between initial message and the previous one

**Comment by ara4n** [comment]
lgtm - thanks!

**Pull request merged**
