### PR TITLE
Add a version update checker and NewVersionBar to show on the UI.

### PR DESCRIPTION
**Pull request by Kegsay**
Polls every 10 minutes then shows a big bar (like desktop notif bar) if there is a new version. Requires the sister PR https://github.com/matrix-org/matrix-react-sdk/pull/133 in order for it to display the bar.

### CODE REVIEW

**Comment by dbkr** [comment]
lgtm

**Comment by Kegsay** [comment]
@dbkr - Sorry, PTAL at https://github.com/vector-im/vector-web/commit/b307a6d64e85eec70d1a5054cf5778bec712b9a7 which allows me to display the current version in `UserSettings` as well!

**Comment by dbkr** [comment]
Actually, it's a little odd that a small part of this is in MatrixChat and the rest is all Vector, especially that the settings component in react now has support for something where the logic all lives in Vector. I guess this is a) because it's much easier to put the bar in MatrixChat and b) more of the general react/vector split, which we have in plenty of other places right now anyway, so lgtm.

**Comment by Kegsay** [comment]
Yeah, it's an *interesting* split. We may want to re-visit it at some point. Deferring responsibility for the version string to the top level (`vector-web`) feels right since the `UserSettings` react component will want to display the "complete" version string, so it needs to know about levels up top which it can't possibly do.

**Pull request merged**
