### PR TITLE
Dbkr/rebrand

### PR DESCRIPTION
**Pull request by dbkr**

### CODE REVIEW

**Comment by slang800** [comment]
what is the name change for?

**Comment by ara4n** [comment]
@slang800 Vector is a bit bland and boring, whereas Riot is rather more catchy and descriptive for an app which aims to tear down the walls of the walled gardens.  https://medium.com/@RiotChat/lets-riot-f5b0aa99dc8e#.kabkbcujg has more details :)

**Comment by 4nd3r** [comment]
sorry for spam, but Vector felt more professional, Riot looks like bad marketing people won the argument.

but in the end it's just a name :>

**Comment by slang800** [comment]
I'm fine with the name change. I'd agree with @4nd3r that vector was more professional (and had a very obvious connection to "matrix"), but so long as you can quickly rename everything before it becomes a well-known project (the point at which a name change is likely to confuse people) I think it'll be fine.

I just asked since there wasn't any documentation on why the change was happening or what it signifies (whether it was a rebranding, or an issue with an existing trademark, or a distinction between the hosted vector client & the project itself). So far, the readme doesn't even mention that it happened.

**Pull request merged**
