### PR TITLE
Implement connection lost bar + resend all

### LINKED ISSUE #197: Show connectivity state and manage resending messages correctly
The screens show the intended design

08 1 no connection
08 2 timed out
08 3 timed out resend individual

### PR DESCRIPTION
**Pull request by Kegsay**
This is missing:
 - Exclamation icon
 - Better CSS

Manually tested and it appears to work. Tested:
 - Contextual menu resend
 - Resend all link
 - No connection bar (appear/disappear on `/events` calls)

Fixes #197.

### CODE REVIEW

**Comment by ara4n** [comment]
LGTM. my only concern is that events doesn't seem to repoll to discover when the server returns? it seems to rely on you issuing a typing notification to 'kick' things to realise that we're back in business...

**Comment by Kegsay** [comment]
It does repoll, but it's not aggressively retrying so we don't kill any homeservers. There is a manual kick option in the SDK but the wireframes have nowhere for it.

**Comment by Kegsay** [comment]
From IRL:
 - Typing notification results in something coming down the event stream which then triggers the state machine from DEAD -> ALIVE. The long timeout on `/events` means that for the 30s that it's polling, it doesn't *know* that it has made the connection and so keeps it in the DEAD state.
 - This can be fixed by using `timeout=0` on pokes when you think you're DEAD.

**Comment by Kegsay** [comment]
This is a JS SDK thing, so merging this.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-js-sdk/commit/6eb896e7

**Pull request merged**
