### PR TITLE
Wmwragg/room tag menu

### LINKED ISSUE #1745: Context Menu: Restyle the LHS menu white
Context Menu: Restyle the LHS menu white

- Needs some small design tweaks and assets to be marked ready

### PR DESCRIPTION
**Pull request by wmwragg**
This should close #1745. A companion branch matrix-org/matrix-react-sdk:wmwragg/room-tag-menu also needs to be merged.

Signed-off-by: William Wragg wm.wragg@gmail.com

### CODE REVIEW

**Comment by ara4n** [comment]
LGTM. One question for @antikewl - is it deliberate that this context menu has a white background whilst the others (mention config; per-message menu) is grey?

**Comment by antikewl** [comment]
Hi, yes, this is deliberate. The two grey menus are on white a background and the white menu is on a coloured background to give contrast.

**Comment by wmwragg** [comment]
I noticed that checks have failed, but they previously passed? I've checked here and all the tests still pass.

**Comment by ara4n** [comment]
i think the failing tests (joining rooms over federation) may be because you haven't merged in develop recently enough. going to merge and see...

**Pull request merged**
